#import "/lib/site.typ": *
#show: base
#meta(title: "Blog")

= Blog

// posts.json is generated by the SSG (ssg/build.ts) before pages compile.
#let posts = json("posts.json")

#if posts.len() == 0 [
  Nothing here yet.
] else {
  elem("ul", class: "posts", {
    for post in posts {
      elem("li", class: "post", {
        elem("a", post.title, class: "post-link", href: page-url(post.page))
        elem("div", post.date, class: "post-meta")
        if post.summary != "" { elem("p", post.summary, class: "post-summary") }
      })
    }
  })
}
