#import "/lib/site.typ": *
#show: template
#meta(title: "Blog")

= Blog

// posts.json is generated by the SSG (ssg/build.mjs) before pages compile.
#let posts = json("posts.json")

#if posts.len() == 0 [
  Nothing here yet.
] else [
  #for post in posts [
    / #post.date: #link("/blog/" + post.slug + ".html")[#post.title] \
      #if post.summary != "" [#text(fill: gray)[#post.summary]]
  ]
]
